added Pausenmenu, Timer and Stars
B4-Group/swe_b4 pull request #14
Opened 2022-11-16 21:24 UTC by krumbs8749

**Addition**

1. Pausenmenu

- Click 'esc' button to open/close the Pausemenu.  When Pausenmenu is opened, the Time.timeScale = 0f (the time of the game is paused)
- 'Fortsetzen' button will close the Pausemenu.
- 'Neu Starten' will reset the timer by calling the 'Timer.ResetTimer()' and the stars by 'Stars.ResetStar()' on click
- 'Level Auswahl' will change the scene to 'Level Auswahl' 
- 'Hauptmenu' will change the scene to 'Hauptmenu'

2. Timer

- Timer is always shown and will be paused when Pausemenu is opened
- To reset time call **Timer.ResetTimer()**
- To get the time (probably for GameOver menu) call **Timer.getTimer()**

3. Stars

- No stars will be shown at the start of the game and will only show stars corresponding to the number of stars collected (currently maximum is 3)
- To increase the number of stars call **Stars.CollectedStars()** -> this is important when later we want to program the collect stars logic
- To reset the number of stars call **Stars.ResetStar()**

**Important: All the UIElement is built using the UIDocument in _Assets/UI/UIScreens/gameUI_**

2022-11-16 21:46 UTC, cr4yfish requested changes
Pausenmenü.cs gibt es doppelt:
"Pausenmenü.cs"
"Pausenmenu.cs"

2022-11-16 22:31 UTC, krumbs8749 commented
> Pausenmenü.cs gibt es doppelt: "Pausenmenü.cs" "Pausenmenu.cs"

Hab schon geloescht

2022-11-16 22:36 UTC, cr4yfish approved these changes

2022-11-17 00:25 UTC, NamoPhoenix approved these changes

2022-11-17 00:30 UTC, merged